### ISSUE TITLE
Not compatible with back-office Prestashop 1.7.7.0

### ISSUE THREAD

**Issue by Frankyet** [myparcelnl/prestashop-deprecated#21]
in the back-office the orders page there is no myparcel button hooked.

**Comment by imagicuus** [comment]
Any updates on this issue?

**Comment by imagicuus** [comment]
Some kind of timeline would be nice to know if I should downgrade Prestashop again or can wait for an update.

I've tried changing the hook from AdminOrder to DisplayAdminOrder, although extra MyParcel code is loaded in the order page, some javacsript errors appeared. There is a jQuery update in prestashop 1.7.7:

### Updated jQuery to latest version
jQuery has been updated to 3.4.1 in Back office (up from 1.11 in legacy pages) and Core theme (up from 2.1.4).

jQuery has changed a lot between v1.11 / v2.1.4 and v3.4.1. This is why jquery migrate was enabled in order to provide a layer of compatibility, but this does not preserve all jQuery capabilities for such old versions.

Modules relying on these old capabilities may experience problems, including but not limited to:

- context property has been removed
- Using dataType in an ajax request won’t trigger the success / done methods if the type of content returned does not match
- jQuery.attr() behavior has evolved, most of the time, you should use jQuery.prop() instead.

https://devdocs.prestashop.com/1.7/modules/core-updates/1.7.7/#updated-jquery-to-latest-version

**Comment by Mitchell-MyParcel** [comment]
@imagicuus We recommend downgrading since we are still researching the compatibility issues.

**Comment by remboyudo** [comment]
Hi @Mitchell-MyParcel what's the status on the compatibility issues? Heb je inmiddels een idee wanneer de module goed werkt in PS 1.7.7?

**Comment by Onno1989** [comment]
I would like to know the same thing. Is anyone working on this?

**Comment by fjutt64** [comment]
I wonder if it is mostly liked to the new order statuses in 1.7.7
When I set the order to Payment remotely accepted; it works.

Anyway I hope this will be resolved soon.

**Comment by PlukZelf** [comment]
Just updated 1.7.7 myparcel not working any more.
Any timeline when a fix is coming ?
Last reaction from Mitchell-MyParcel is almost 2 months ago !

**Comment by fjutt64** [comment]
> @imagicuus We recommend downgrading since we are still researching the compatibility issues.

@Mitchell-MyParcel Is there any update? it works partially for me. looks as if the new statuses are causing the issue.
If you want I can share my backoffice for you to check. It would be great if we can get this fixed. 
Cheers,
Frans

**Comment by Mitchell-MyParcel** [comment]
@PlukZelf @fjutt64: @Onno1989 We are currently testing the update. I will place an update in this thread (probably tomorrow or Wednesday) once I can say something with more certainty.

**Comment by Mitchell-MyParcel** [comment]
@imagicuus @Frankyet @Onno1989 @remboyudo @PlukZelf The update is not finished yet.

I think it is good to explain why this has taken longer than usual. For reasons not entirely under our control we had to rebuild the entire Prestashop plug-in almost from scratch. We started this way before v1.7.7.7 was launched and were in the final building stages when 1.7.7.7 was released. Because of this the update to v1.7.7.7. and finishing the new plugin got intertwined. Of course we did take a look at the current plug-in to see if we could find a good way to update it, but soon decided that we could better wait on the new plug-in.

We understand that you are anxiously awaiting the new version and we are pushing really hard to get it out there as soon as possible. I expect to have another update before the end of this week.

**Comment by PlukZelf** [comment]
Explaination is really appreciated.

**Comment by fjutt64** [comment]
@Mitchell-MyParcel  Thanks for explaining. Much appreciated! 

Will this new version also cover Letterbox parcel for all EU like one now can book at postnl?

Regards,
Frans

**Comment by Mitchell-MyParcel** [comment]
@fjutt64 Wa have been receiving more questions about this product lately. We do not yet offer letterbox parcels for international shipments. Last year we research this product but we paused this because then you needed to hand over a minimum of letterbox parcel per day per customer in a postal bag tied with a special bag label. Both needed to be ordered from the PostNL webshop with a PostNL business account. We are currently checking if the proposition has changed since then.

With regards to the update. Today the last issues from our test findings were fixed. We will do a retest tomorrow en and if needed the day after. I will keep you updated.

**Comment by fjutt64** [comment]
@Mitchell-MyParcel 

Awesome news on the progress!!!
As to Letterboxes. Indeed now you do to have a minimum restriction via the postnl site. That was a stupid restriction from them. Fingers crossed.

Regards,
Frans

**Comment by Mitchell-MyParcel** [comment]
After the retest 2 issues were identified as not yet fixed. Our development partner will try fix these tomorrow and hopefully we can do a retest right after. I have good hopes we will release the new version as beta very soon.

**Comment by JanMiddelkoop** [comment]
@Mitchell-MyParcel Is there any news on this? I'd love to help test a release candidate if you have it.

**Comment by fjutt64** [comment]
@Mitchell-MyParcel Here the same! Happy to test a release candidate. :) Thanks for your support.

**Comment by Mitchell-MyParcel** [comment]
@JanMiddelkoop @fjutt64 : The final tests are done. An installation package is being prepared. Since the plugin is entirely new we will release it as a beta. We had to make a decision to continue developing or releasing it with some known issues and we chose the second option because the basic functionality should be ok and you are all eagerly awaiting the release. I am happy to share this version with you as soon as we have it, but I must warn you that we won't be able to pick up and stamp out bugs right-away because we are also still in the proces of instructing our support department and technical team. For those willing to betatest we will share the version including a list of known issues on github next week.

**Comment by Mitchell-MyParcel** [comment]
@fjutt64 @JanMiddelkoop @imagicuus @Frankyet @Onno1989 @remboyudo 

We have just released the new Prestashop plug-in as a beta. Please read the release notes and instructions carefully because this is an entirely new and rebuilt plug-in. We went live with some known issues. These can also be found in the release notes. Also we will start supporting this plugin next Monday. If you encounter any issues that have not yet been reported please place them in the new Prestashop entry.

The new repo, plugin and release notes can be found here:

https://github.com/myparcelnl/prestashop/releases/tag/v1.0.0

**Comment by fjutt64** [comment]
@Mitchell-MyParcel Thanks. will go and try it asap

**Comment by JanMiddelkoop** [comment]
@Mitchell-MyParcel Thanks. First breaking issue is reported. :-)
